name: flutter_verification_code_input
author: loinp<nploi1998@gmail.com>
homepage: https://github.com/nploi/flutter_verification_code_input
description: A Flutter package that help you create a verification input.
version: 0.0.1

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0